name: CIOOS Atlantic Docker tagged

on:
 release:
  types: [published]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/cioosatlantic/docker-erddap:${{ github.event.release.tag_name }}
        docker push docker.io/cioosatlantic/docker-erddap:${{ github.event.release.tag_name }}
