name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin docker.io
        docker build . --file Dockerfile --tag docker.io/cioosatlantic/docker-erddap:$GITHUB_SHA
        docker push docker.io/cioosatlantic/docker-erddap:$GITHUB_SHA
